{"frames":[{"func":"gitcreds::gitcreds_set()","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"gitcreds_set_replace(url, current)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"throw(new_error(\"gitcreds_abort_replace_error\"))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"stop(cond)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error in throw(new_error(\"gitcreds_abort_replace_error\")) : \n  User aborted updating credentials\n"}